// NOTE: This file is automatically generated and should not be edited by hand
import Foundation

struct Strings {
    static var my_string: String { return NSLocalizedString("my_string", comment: "") }
}
