// NOTE: This file is automatically generated and should not be edited by hand
import Foundation

struct Strings {
    static func string(arg1: String) -> String { return String.localizedStringWithFormat(NSLocalizedString("string", comment: ""), arg1) }
}
