// NOTE: This file is automatically generated and should not be edited by hand
import Foundation

struct Strings {
    static func int_string(arg1: Int) -> String { return String.localizedStringWithFormat(NSLocalizedString("int_string", comment: ""), arg1) }
}
