// NOTE: This file is automatically generated and should not be edited by hand
import Foundation

struct Strings {
    static func multi_arg_string(arg1: Int, _ arg2: String, _ arg3: Int) -> String { return String.localizedStringWithFormat(NSLocalizedString("multi_arg_string", comment: ""), arg1, arg2, arg3) }
}
