// NOTE: This file is automatically generated and should not be edited by hand
import Foundation

struct Strings {
    static var percent_string: String { return NSLocalizedString("percent_string", comment: "") }
}
