// NOTE: This file is automatically generated and should not be edited by hand
import Foundation

struct Strings {
    static func named_arg(name name: String) -> String { return String.localizedStringWithFormat(NSLocalizedString("named_arg", comment: ""), name) }
    static func named_args(title title: String, name: String) -> String { return String.localizedStringWithFormat(NSLocalizedString("named_args", comment: ""), title, name) }
}
